# Información básica del sitio
title: "Mi sitio en GitHub Pages"
description: "Un sitio web creado con Jekyll y GitHub Pages"

# Markdown y opciones de formato
markdown: kramdown
highlighter: rouge
include:
  - _includes/math.html

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one